### ISSUE TITLE
"Invalid URL" TypeError from the UI as it talks to the API

### ISSUE THREAD

**Issue by basilesimon** [digitalevidencetoolkit/deptoolkit-node-api#61]
Since we've moved to SvelteKit, the [available `fetch` object](https://kit.svelte.dev/docs#loading-input-fetch) is a little different... which requires an absolute URL, otherwise this error crops up:  

```
(node:96340) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /api/list-docs
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
```

See `ui/src/lib/Ledger/index.ts` for the culprits:

```js
const res = await fetch(`api/list-docs`);
```

 [This issue](https://github.com/sveltejs/kit/issues/1593) outlines that we need to move to this initial [`load()`](https://kit.svelte.dev/docs#loading)

**Comment by basilesimon** [comment]
Must reassess in light of [this other PR](https://github.com/digitalevidencetoolkit/deptoolkit/pull/74)
